version: '3.9'

services:
  mssql:
    image: ${DOCKER_REGISTRY-}dbsql
    build:
      context: .
      dockerfile: ./filedb/Dockerfile

    #image: mcr.microsoft.com/mssql/server:2019-latest
    #ports:
    #  - 1433:1433
    #volumes:
    #  - ~/apps/mssql/data:/var/lib/mssqlql/data
    #environment:
    #  - ACCEPT_EULA=Y
    #  - SA_PASSWORD=mssql1Ipw

  vuelos.webapi:
    image: ${DOCKER_REGISTRY-}vueloswebapi
    build:
      context: .
      dockerfile: ./Dockerfile
