
USE [master]
GO
/****** Object:  Database [VuelosDb]    Script Date: 1/7/2022 22:41:42 ******/
CREATE DATABASE [VuelosDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VuelosDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VuelosDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VuelosDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VuelosDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [VuelosDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VuelosDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VuelosDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VuelosDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VuelosDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VuelosDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VuelosDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [VuelosDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VuelosDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VuelosDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VuelosDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VuelosDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VuelosDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VuelosDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VuelosDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VuelosDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VuelosDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VuelosDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VuelosDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VuelosDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VuelosDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VuelosDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VuelosDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VuelosDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VuelosDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [VuelosDb] SET  MULTI_USER 
GO
ALTER DATABASE [VuelosDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VuelosDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VuelosDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VuelosDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VuelosDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VuelosDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [VuelosDb] SET QUERY_STORE = OFF
GO
USE [VuelosDb]
GO
/****** Object:  Table [dbo].[Aeronave]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aeronave](
	[IdAeronave] [uniqueidentifier] NOT NULL,
	[Estado] [varchar](50) NULL,
	[NroAsientos] [int] NULL,
	[Marca] [varchar](50) NULL,
	[Modelo] [varchar](50) NULL,
	[CapacidadCarga] [decimal](18, 2) NULL,
	[CapacidadTanque] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Aeronave] PRIMARY KEY CLUSTERED 
(
	[IdAeronave] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Aeropuerto]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aeropuerto](
	[IdAeropuerto] [uniqueidentifier] NOT NULL,
	[IdLugar] [uniqueidentifier] NULL,
	[SecuenciaVuelo] [int] NULL,
	[Nombre] [varchar](50) NULL,
 CONSTRAINT [PK_Aeropuerto] PRIMARY KEY CLUSTERED 
(
	[IdAeropuerto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cargo]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cargo](
	[IdCargo] [uniqueidentifier] NOT NULL,
	[Descripcion] [varchar](50) NULL,
 CONSTRAINT [PK_Cargo] PRIMARY KEY CLUSTERED 
(
	[IdCargo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Itinerario]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Itinerario](
	[IdItinerario] [uniqueidentifier] NOT NULL,
	[IdPista] [uniqueidentifier] NULL,
	[IdAeronave] [uniqueidentifier] NULL,
	[NroVuelo] [int] NULL,
	[FechaHoraDesde] [datetime] NULL,
	[FechaHoraHasta] [datetime] NULL,
 CONSTRAINT [PK_Itinerario] PRIMARY KEY CLUSTERED 
(
	[IdItinerario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Localidad]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Localidad](
	[IdLocalidad] [uniqueidentifier] NOT NULL,
	[Nombre] [varchar](50) NULL,
 CONSTRAINT [PK_Localidad] PRIMARY KEY CLUSTERED 
(
	[IdLocalidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Lugar]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lugar](
	[IdLugar] [uniqueidentifier] NOT NULL,
	[IdLocalidad] [uniqueidentifier] NULL,
 CONSTRAINT [PK_Lugar] PRIMARY KEY CLUSTERED 
(
	[IdLugar] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pista]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pista](
	[IdPista] [uniqueidentifier] NOT NULL,
	[IdAeropuerto] [uniqueidentifier] NULL,
 CONSTRAINT [PK_Pista] PRIMARY KEY CLUSTERED 
(
	[IdPista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tripulacion]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tripulacion](
	[IdTripulacion] [uniqueidentifier] NOT NULL,
	[IdVuelo] [uniqueidentifier] NOT NULL,
	[IdCargo] [uniqueidentifier] NULL,
 CONSTRAINT [PK_Tripulacion] PRIMARY KEY CLUSTERED 
(
	[IdTripulacion] ASC,
	[IdVuelo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tripulante]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tripulante](
	[IdTripulante] [uniqueidentifier] NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Apellido] [varchar](50) NULL,
	[MillasVuelo] [decimal](18, 2) NULL,
	[HorasVuelo] [int] NULL,
 CONSTRAINT [PK_Tripulante] PRIMARY KEY CLUSTERED 
(
	[IdTripulante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vuelo]    Script Date: 1/7/2022 22:41:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vuelo](
	[IdVuelo] [uniqueidentifier] NULL,
	[IdLugarOrigen] [uniqueidentifier] NULL,
	[IdLugarDestino] [uniqueidentifier] NULL,
	[IdItinerario] [uniqueidentifier] NULL,
	[FechaHoraPartida] [datetime] NULL,
	[FechaHoraLlegada] [datetime] NULL,
	[TipoVuelo] [varchar](10) NULL,
	[MilasVuelo] [decimal](18, 2) NULL,
	[TiempoVuelo] [int] NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [VuelosDb] SET  READ_WRITE 
GO
